### PR TITLE
Front End Styling and code cleanup round 1

### PR DESCRIPTION
**Pull request by Liz303**
There's a lot going on in the PR, overall I've tried to get all the new DVLP DNVR 2020 styling and layout into all the major components. Where possible I've cleaned up sass files and component files to follow a similar structure. I have also added in a few new components (about/contact being main ones) to help add more clarity to the site and user experience.

### CODE REVIEW

**Comment by kylecoberly** [comment]
Hey Liz! First pass through the code looks good, checking it out locally

**Comment by kylecoberly** [comment]
This looks great! Some notes:

* The homepage map and the location names overrun the container on mobile
* The footer doesn't stretch all the way across on wide screens (intentional?)
* I'm not sure about the accessibility of the error text on the login page. I think all of the other parts of the page are ok, but the red text probably needs an opaque background too
* The buy button on the tickets page is hidden by the footer on mobile (same for the schedule page)

I still need to check out the stuff that's behind logins and some of the copy needs to get updated (I'll get some folks on that), but this is great work!

**Comment by Liz303** [comment]
@kylecoberly I have a lot more changes in another branch. Should I put those commits into this pull request or create a new one.

**Comment by kylecoberly** [comment]
Merge them into this one please!

**Comment by Liz303** [comment]
@kylecoberly I just merged in my branch with newest code which should address some (but not all of your comments). This code is very much still in development and not really ready for design feedback from anyone but Tim at this point in time since it's a WIP still. Hoping we can get this stuff up on a staging so that Tim can be looking at it and getting me feedback so I can continue iterating. But again THIS IS NOT COMPLETE yet, still a WIP just want to get something onto staging for Tim.

**Comment by Liz303** [comment]
@kylecoberly This is now ready for your review! Let me know if you see anything we missed here.

**Comment by kylecoberly** [comment]
Cool, noted!

**Comment by kylecoberly** [comment]
There's a couple of copy changes needed, but we can handle this. This look great, WAY TO GO GANG!!

**Pull request merged**
